// <auto-generated />
using System;
using AI_CampaignGenerator.Presistence.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI_CampaignGenerator.Presistence.Data.Migrations
{
    [DbContext(typeof(AICampaignGeneratorDbContext))]
    [Migration("20260126163821_EntitiesModulesTables")]
    partial class EntitiesModulesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdTone")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("GeneratedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IdealCaption")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("IdealHashtags")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ImagePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UploadedImageURL")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("AIGeneratedContent");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContentImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("AIGeneratedImages");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.CmpaignsModule.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignGoal")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Campaign_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("GeneratedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.ProductModule.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GenderFocus")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetAudiencePersona")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("USP")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.ProductModule.ProductImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.UserModule.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("JoinDate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("ValidEmailCheck", "Email Like '_%@_%._%'");

                            t.Property("JoinDate")
                                .HasColumnName("JoinDate1");
                        });
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContent", b =>
                {
                    b.HasOne("AI_CampaignGenerator.Domain.Entities.CmpaignsModule.Campaign", "Campaign")
                        .WithMany("AIContents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContentImages", b =>
                {
                    b.HasOne("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContent", "Content")
                        .WithMany("Images")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.CmpaignsModule.Campaign", b =>
                {
                    b.HasOne("AI_CampaignGenerator.Domain.Entities.ProductModule.Product", "Product")
                        .WithMany("Campaigns")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_CampaignGenerator.Domain.Entities.UserModule.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.ProductModule.Product", b =>
                {
                    b.HasOne("AI_CampaignGenerator.Domain.Entities.UserModule.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.ProductModule.ProductImages", b =>
                {
                    b.HasOne("AI_CampaignGenerator.Domain.Entities.ProductModule.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.Ai_GeneratedContentModule.AIGeneratedContent", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.CmpaignsModule.Campaign", b =>
                {
                    b.Navigation("AIContents");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.ProductModule.Product", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("AI_CampaignGenerator.Domain.Entities.UserModule.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
